services:
  - type: web
    name: automata-system
    env: python
    buildCommand: |
      apt-get update && apt-get install -y graphviz
      pip install -r requirements.txt
    startCommand: gunicorn main:app